spring:
  #数据源的配置
  datasource:
    url: jdbc:mysql://rm-uf69rclygox273t10.mysql.rds.aliyuncs.com:3306/electric_bicycle_pro?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: jjdc_123
    password: jjdc_99bicycle
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 10

  #hibernate配置
  jpa:
    database: mysql
    show-sql: false
    hibernate:
       #Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
         current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext


  #mvc视图的配置
  mvc:
     view:
       prefix: /page/
       suffix: .jsp




